RADIO_DATA = [
    {
        "frequency": "95.2",
        "genres": ["Mainstream Pop", "Top Hits"],
        "id": "0",
        "name": "Athens Deejay FM 95.2",
        "poster": "https://cdn.e-radio.gr/logos/gr/500/deejay.png",
        "url": "http://94.23.0.114:41972",
    },
    {
        "frequency": "89.2",
        "genres": ["Mainstream Pop", "Top Hits"],
        "id": "1",
        "name": "Music 89.2",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/music892-athens.png",
        "url": "https://stream.radiojar.com/k0hua7u1yk5tv",
    },
    {
        "frequency": "88.9",
        "genres": ["Pop", "Top Hits"],
        "id": "2",
        "name": "HIT 88.9",
        "poster": "https://mmo.aiircdn.com/342/5e3c29bb9e2f3.png",
        "url": "https://stream.radiojar.com/wgv51425e3quv",
    },
    {
        "frequency": "106.2",
        "genres": ["Mainstream House", "Pop"],
        "id": "3",
        "name": "MAD RADIO 106.2",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/madradio1.png",
        "url": "http://mediaserver.mad.tv/stream",
    },
    {
        "frequency": "92.6",
        "genres": ["Electronic House"],
        "id": "4",
        "name": "Best Radio 92.6",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/bestradio.png",
        "url": "http://best.live24.gr/best1222",
    },
    {
        "frequency": "102.50",
        "genres": [],
        "id": "5",
        "name": "Athens Voice 102.5",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/athensvoicefm.png",
        "url": "http://nitro.live24.gr/nitro4555",
    },
    {
        "frequency": "94.30",
        "genres": [],
        "id": "6",
        "name": "ELLADA FM 94.3",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ellada943.jpg",
        "url": "http://cast4.magicstreams.gr:10198",
    },
    {
        "frequency": "87.70",
        "genres": ["Electronic House"],
        "id": "7",
        "name": "En Lefko 87.7",
        "poster": "https://mm.aiircdn.com/630/5dd2b1d909000.png",
        "url": "https://stream.radiojar.com/enlefko877",
    },
    {
        "frequency": "96.60",
        "genres": ["Easy Listening"],
        "id": "8",
        "name": "Pepper 96.6",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/pepper.jpg",
        "url": "https://stream.radiojar.com/pepper.m4a",
    },
    {
        "frequency": "92.90",
        "genres": ["Adult Contemponary"],
        "id": "9",
        "name": "Kiss FM 92.9",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/kissfmathens.png",
        "url": "http://kissfm.live24.gr/kiss2111",
    },
    {
        "frequency": "97.20",
        "genres": ["Easy Listening"],
        "id": "10",
        "name": "Easy 97.2",
        "poster": "https://media.bauerradio.com/image/upload/c_crop,g_custom/v1641202384/brand_manager/stations/x4gn1gt9ip69ij5tknsl.png",
        "url": "https://stream.radiojar.com/cthtwxk5yvduv",
    },
    {
        "frequency": "92.00",
        "genres": ["Easy Listening"],
        "id": "11",
        "name": "Galaxy 92.0",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/galaxypink.png",
        "url": "http://galaxy.live24.gr/galaxy9292",
    },
    {
        "frequency": "107.20",
        "genres": ["Easy Listening"],
        "id": "12",
        "name": "Blue Space 107.2",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/bluespacefmlogo1072.png",
        "url": "https://cast5.streamhost.gr:8104/stream",
    },
    {
        "frequency": "100.60",
        "genres": ["Easy Listening"],
        "id": "13",
        "name": "Nostos FM 100,6",
        "poster": "https://www.shareicon.net/data/128x128/2016/08/04/806702_music_512x512.png",
        "url": "https://neos.win:37878/stream",
    },
    {
        "frequency": "96.30",
        "genres": ["Rock"],
        "id": "14",
        "name": "RED 96.3",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/Red.png",
        "url": "https://stream.radiojar.com/redfm963",
    },
    {
        "frequency": "96.90",
        "genres": ["Rock"],
        "id": "15",
        "name": "Rock FM 96.9",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/rockfm.png",
        "url": "http://rockfmlive.mdc.akamaized.net/strmRCFm/userRCFm/playlist.m3u8",
    },
    {
        "frequency": "105.20",
        "genres": ["Greek Rock"],
        "id": "16",
        "name": "Atlantis FM 105,2",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/atlantisradio.png",
        "url": "http://85.10.206.222:8012/stream.mp3",
    },
    {
        "frequency": "89.80",
        "genres": ["Greek Mainstream"],
        "id": "17",
        "name": "DROMOS FM 89.8",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/dromosfm.png",
        "url": "https://stream.rcs.revma.com/10q3enqxbfhvv",
    },
    {
        "frequency": "102.20",
        "genres": ["Greek Mainstream"],
        "id": "18",
        "name": "Sfera 102.2",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/sfera-athens.png",
        "url": "http://sfera.live24.gr/sfera4132",
    },
    {
        "frequency": "92.30",
        "genres": ["Greek Mainstream"],
        "id": "19",
        "name": "Lampsi 92.3",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/lampsifm.png",
        "url": "http://lampsifmlive.mdc.akamaized.net/strmLampsi/userLampsi/playlist.m3u8",
    },
    {
        "frequency": "94.90",
        "genres": ["Greek Mainstream"],
        "id": "20",
        "name": "Rythmos 94.9",
        "poster": "https://www.shareicon.net/data/128x128/2016/08/04/806702_music_512x512.png",
        "url": "https://stream.radiojar.com/g4tyehk5yvduv",
    },
    {
        "frequency": "104.00",
        "genres": ["Mainstream Pop", " Top Hits"],
        "id": "21",
        "name": "Athens Party 104.0",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/athensparty.png",
        "url": "https://radio.streamings.gr:9006/stream",
    },
    {
        "frequency": "101.60",
        "genres": ["Mainstream Pop", " Top Hits"],
        "id": "22",
        "name": "Paradise Radio 101.6",
        "poster": "https://cdn.e-radio.gr/logos/gr/500/paradise1016.jpg",
        "url": "http://213.239.206.179:8850",
    },
    {
        "frequency": "98.60",
        "genres": ["Greek", " Folk"],
        "id": "23",
        "name": "Derti FM 98.6",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/dertiwebradio.png",
        "url": "http://derti.live24.gr/derty1000",
    },
    {
        "frequency": "102.70",
        "genres": ["Greek", " Folk"],
        "id": "24",
        "name": "Palmos Radio FM 102.7"
        "www.palmosradio.gr *",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/palmosradio1027.jpg",
        "url": "http://s6.onweb.gr:8010/;stream",
    },
    {
        "frequency": "93.20",
        "genres": ["Art Music", " Folk", " Greek"],
        "id": "25",
        "name": "Ellinikos 93.2",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ellinikos932.png",
        "url": "http://orange.live24.gr/orange9320",
    },
    {
        "frequency": "98.60",
        "genres": ["Art Music", " Folk", " Greek"],
        "id": "26",
        "name": "Mousikos Athens 98.6",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/mousikosathina.png",
        "url": "https://netradio.live24.gr/mousikos986",
    },
    {
        "frequency": "101.30",
        "genres": ["Art Music", " Folk", " Greek"],
        "id": "27",
        "name": "DIESI FM 101.3",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/diesi.png",
        "url": "http://diesi.live24.gr/diesi1013",
    },
    {
        "frequency": "99.20",
        "genres": ["Art Music", " Greek"],
        "id": "28",
        "name": "Melodia, Athens (Art Music, Greek) - Melodia",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/melodia.png",
        "url": "https://stream.radiojar.com/8du64725e3quv",
    },
    {
        "frequency": "88.00",
        "genres": ["Art Music", " Greek"],
        "id": "29",
        "name": "Menta 88.0",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/menta88.png",
        "url": "https://stream.radiojar.com/menta.aac",
    },
    {
        "frequency": "97.50",
        "genres": ["Easy Listening", " Greek"],
        "id": "30",
        "name": "Love Radio 97.5",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/loveradio2018.png",
        "url": "http://loveradio.live24.gr/loveradio-1000",
    },
    {
        "frequency": "106.40",
        "genres": ["Greek Mainstream", " Folk"],
        "id": "31",
        "name": "Radio Argosaronikos FM 106,4",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/radioargosaronikos.png",
        "url": "http://s3.onweb.gr:8536",
    },
    {
        "frequency": "106.50",
        "genres": ["Greek Folk"],
        "id": "32",
        "name": "Athens Radio 106.5",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/athensfm1065.png",
        "url": "http://89.163.217.252:9400/stream",
    },
    {
        "frequency": "99.50",
        "genres": ["Folk", " Old Greek"],
        "id": "33",
        "name": "Peiratikos, Athens (Folk, Old Greek) - No Name",
        "poster": "https://www.shareicon.net/data/128x128/2016/08/04/806702_music_512x512.png",
        "url": "http://89.163.217.252:9800",
    },
    {
        "frequency": "103.20",
        "genres": ["Greek Folk"],
        "id": "34",
        "name": "Blackman 103.2",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/blackman.png",
        "url": "http://alpha-stream.eu:9326/;.mp3",
    },
    {
        "frequency": "91.40",
        "genres": ["Tranditional", " Greek"],
        "id": "35",
        "name": "LyraFM 91.4",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/lyrafm.png",
        "url": "http://172.93.237.106:8271/live",
    },
    {
        "frequency": "87.50",
        "genres": ["Tranditional", " Greek"],
        "id": "36",
        "name": "Kriti FM 87.5",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/kritifm_875.png",
        "url": "http://s3.onweb.gr:8878",
    },
    {
        "frequency": "88.60",
        "genres": ["Kids", " Greek"],
        "id": "37",
        "name": "Kids Radio 88.6",
        "poster": "https://www.shareicon.net/data/128x128/2016/08/04/806702_music_512x512.png",
        "url": "https://stream.radiojar.com/64p6ktzntg0uv",
    },
    {
        "frequency": "90.40",
        "genres": ["Local", " Greek"],
        "id": "38",
        "name": "Kanali 1 Peiraia 90.4",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/kanali1peiraia.png",
        "url": "https://netradio.live24.gr/kanali1peiraia",
    },
    {
        "frequency": "94.00",
        "genres": ["Local", " Greek"],
        "id": "39",
        "name": "Epikoinwnia 94.0",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/epikoinonia.jpg",
        "url": "https://cc.vmakerhost.com/proxy/epikoinonia94fm",
    },
    {
        "frequency": "105.50",
        "genres": ["News"],
        "id": "40",
        "name": "Sto Kokkino 105.5",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/stokokkino1055.png",
        "url": "https://stream.radiojar.com/kokkino-ath.mp3",
    },
    {
        "frequency": "98.90",
        "genres": ["News"],
        "id": "41",
        "name": "Alpha 98.9",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/989alpha.png",
        "url": "https://stream.radiojar.com/xcdg6yggzfeuv",
    },
    {
        "frequency": "97.80",
        "genres": ["News"],
        "id": "42",
        "name": "Real FM 97.8",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/realfm.png",
        "url": "http://realfm2.live24.gr:80/realfm",
    },
    {
        "frequency": "90.10",
        "genres": ["News"],
        "id": "43",
        "name": "Parapolitika 90.1",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/parapolitikafm.png",
        "url": "http://netradio.live24.gr/athinaradio",
    },
    {
        "frequency": "98.30",
        "genres": ["News"],
        "id": "44",
        "name": "Athina 98.4",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/athina984.png",
        "url": "http://athina984.live24.gr/athina984",
    },
    {
        "frequency": "100.30",
        "genres": ["News"],
        "id": "45",
        "name": "Skai 100.3",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/skai1003.png",
        "url": "http://netradio.live24.gr/skai1003",
    },
    {
        "frequency": "90.60",
        "genres": ["News"],
        "id": "46",
        "name": "Art 90,6",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/artfm906.png",
        "url": "https://stream.webmonster.gr/artfm906",
    },
    {
        "frequency": "94.60",
        "genres": ["Sports News"],
        "id": "47",
        "name": "Nova Sports FM 94.6",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/sportfm946.png",
        "url": "http://sportfm.live24.gr/sportfm7712",
    },
    {
        "frequency": "103.30",
        "genres": ["Sports News"],
        "id": "48",
        "name": "Sport 24 103.3",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/sport24radio.png",
        "url": "http://n04.radiojar.com/r2aezx4wxxquv",
    },
    {
        "frequency": "104.90",
        "genres": ["Sports News"],
        "id": "49",
        "name": "Over FM 104.9",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/overfm.png",
        "url": "http://netradio.live24.gr/overfm-internet",
    },
    {
        "frequency": "89.50",
        "genres": ["Religion"],
        "id": "50",
        "name": "Ekklisia Ellados 89.5",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ecclesia.png",
        "url": "http://85.10.206.222:8002",
    },
    {
        "frequency": "104.30",
        "genres": ["Religion"],
        "id": "51",
        "name": "Radiofwno Xristianismos, Athens (Religion) - ChristianityRadio",
        "poster": "https://www.shareicon.net/data/128x128/2016/08/04/806702_music_512x512.png",
        "url": "https://uk1.streamingpulse.com/ssl/ChristianityRadio",
    },
    {
        "frequency": "Era",
        "genres": ["News"],
        "id": "52",
        "name": "Era 1 (1 Programma)",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ert-protoprogramma.png",
        "url": "http://radiostreaming.ert.gr/ert-proto",
    },
    {
        "frequency": "Era",
        "genres": ["Art Music"],
        "id": "53",
        "name": "Era 2 (2 Programma)",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ert-deuteroprogramma.png",
        "url": "http://radiostreaming.ert.gr/ert-deftero",
    },
    {
        "frequency": "Era",
        "genres": ["Classic Music"],
        "id": "54",
        "name": "Era 3 (3 Programma)",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ert-tritoprogramma.png",
        "url": "http://radiostreaming.ert.gr/ert-trito",
    },
    {
        "frequency": "Era",
        "genres": ["Sports News"],
        "id": "55",
        "name": "Era Sport",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ert-sport.png",
        "url": "http://radiostreaming.ert.gr/ert-erasport",
    },
    {
        "frequency": "Era",
        "genres": ["Jazz", " Ethnic"],
        "id": "56",
        "name": "Ert Kosmos",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ert-kosmos.png",
        "url": "http://radiostreaming.ert.gr/ert-kosmos",
    },
    {
        "frequency": "Era",
        "genres": ["News", " World"],
        "id": "57",
        "name": "Ert Voice of Greece",
        "poster": "https://cdn.e-radio.gr/logos/gr/big/ert-foni.png",
        "url": "http://radiostreaming.ert.gr/ert-voiceofgreece",
    },
]
